apiVersion: v2
name: bookstack
description: A Helm chart for Kubernetes

type: application

version: "0.1.0+up25.2.3"

appVersion: "25.2.3"

dependencies:
  - name: mariadb
    version: ">=20.0.0 <21.0.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: db
    condition: db.enabled
  - name: redis
    version: ">=21.0.0 <22.0.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled
