apiVersion: v2
name: bookstack
description: |
  Deploys the BookStack wiki platform on Kubernetes with optional MariaDB and Redis sub-charts.

type: application

version: "0.1.0+up25.5.0"

appVersion: "25.5.0"

dependencies:
  - name: mariadb
    version: ">=20.0.0 <21.0.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: db
    condition: db.enabled
  - name: redis
    version: ">=21.0.0 <22.0.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled

annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Git Repository
      url: https://git.morlana.online/f.weber/bookstack-chart
    - name: Issues
      url: https://github.com/flweber/helm-bookstack/issues
    - name: GitHub Mirror
      url: https://github.com/flweber/helm-bookstack
  artifacthub.io/maintainers: |
    - name: Florian Weber
      email: kosmos@morlana.net
  artifacthub.io/signKey: |
    fingerprint: 8975 6E20 1E4C 99B1 A2E9  5712 DF7D F259 CD8F CAAA
    url: https://raw.githubusercontent.com/flweber/helm-bookstack/refs/heads/main/pubkeys/morlana.asc
  artifacthub.io/changes: |
    - kind: changed
      description: ✦ Packages upstream BookStack v25.5.0
      links:
        - name: Release Notes
          url: https://github.com/solidnerd/docker-bookstack/releases/tag/25.5.0
        - name: Project homepage
          url: https://www.bookstackapp.com/
